import './globals.css'
import { Inter, Darker_Grotesque } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const DarkerGrotesque = Darker_Grotesque({
  subsets: ['latin'],
  weight: ['300','400','500','600','700', '800', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={DarkerGrotesque.className}>{children}</body>
    </html>
  )
}
